{
 "title": "Ingress CPU usage vs Endpoint Traffic",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "target",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"ingress-nginx\"}[$__rate_interval]))",
     "legendFormat": "{{.pod}}"
    }
   ]
  },
  {
   "title": "Data Recieved/Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container) (increase(process_network_receive_bytes_total{container=\"controller\", namespace=\"ingress-nginx\"}[$__rate_interval]))",
     "legendFormat": "in"
    },
    {
     "expr": "- sum by(container) (increase(process_network_transmit_bytes_total{container=\"controller\", namespace=\"ingress-nginx\"}[$__rate_interval]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Endpoint Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(vhost) (count_over_time({namespace=\"ingress-nginx\", container=\"controller\"} | json | __error__=`` [$__interval]))",
     "legendFormat": "{{.vhost}}"
    }
   ]
  }
 ]
}