{
 "title": "K8up backups",
 "description": "all the data we get from k8up as a dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Metrics Datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Logs Datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "All Backups",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8up_jobs_successful_counter{jobType=\"backup\"})",
     "legendFormat": "Successes"
    },
    {
     "expr": "count(k8up_jobs_failed_counter{jobType=\"backup\"})",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Failures by app name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\"})",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Successes by app name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\"})",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "🦊 Forgejo Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Forgejo",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 148 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - Forgejo",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 148 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - Forgejo",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 148 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Forgejo",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 243 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Forgejo",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 243 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Forgejo",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 243 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for Forgejo",
     "type": "logs",
     "description": "logs for k8up for GoToSocial",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 249 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"forgejo\", container=\"backup\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "👻 Ghost",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Ghost",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 149 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"ghost\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - Ghost",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 149 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"ghost\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - Ghost",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 149 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"ghost\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - ghost",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 225 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"ghost\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - ghost",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 225 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"ghost\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - ghost",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 225 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"ghost\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for ghost",
     "type": "logs",
     "description": "logs for k8up for GoToSocial",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 231 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"ghost\", container=\"backup\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "🦥 GoToSocial Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - GoToSocial",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 347 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - GoToSocial",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 347 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - GoToSocial",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 347 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - GoToSocial",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 353 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - GoToSocial",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 353 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - GoToSocial",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 353 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for GotoSocial",
     "type": "logs",
     "description": "logs for k8up for GoToSocial",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 359 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"gotosocial\", container=\"backup\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "🛟 Harbor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - harbor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"harbor\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - harbor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"harbor\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - harbor",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"harbor\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Habor",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"harbor\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Harbor",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"harbor\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Harbor",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"harbor\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for harbor",
     "type": "logs",
     "description": "logs for k8up for harbor",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"harbor\", container=\"backup\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "🛜 Home Assistant Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Home Assistant",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - home assistant",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - home assistant",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Home Assistant",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Home Assistant",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Home Assistant",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for home assistant",
     "type": "logs",
     "description": "logs for k8up for home assistant",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"home-assistant\", container=\"backup\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "🪼 Jellyfin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - jellyfin",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 152 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"jellyfin\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - jellyfin",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 152 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"jellyfin\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - jellyfin",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 152 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"jellyfin\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Jellyfin",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{namespace=\"jellyfin\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Jellyfin",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"jellyfin\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - jellyfin",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"jellyfin\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for jellyfin",
     "type": "logs",
     "description": "logs for k8up for mastodon",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 183 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"jellyfin\", container=\"backup\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "🐘 Mastodon Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Mastodon",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 787 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - mastodon",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 787 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{instance=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - mastodon",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 787 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Mastodon",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 793 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Mastodon",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 793 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Mastodon",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 793 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for mastodon",
     "type": "logs",
     "description": "logs for k8up for mastodon",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 799 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"mastodon\", container=\"backup\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "💬 Matrix Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Matrix",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 807 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - Matrix",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 807 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{instance=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - Matrix",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 807 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Matrix",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 813 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Matrix",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 813 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Matrix",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 813 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for Matrix",
     "type": "logs",
     "description": "logs for k8up for matrix",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 818 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"matrix\", container=\"backup\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "☁️ Nextcloud Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Nextcloud",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 844 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - Nextcloud",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 844 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{instance=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - Nextcloud",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 844 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Nextcloud",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 850 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Nextcloud",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 850 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Nextcloud",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 850 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for Nextcloud",
     "type": "logs",
     "description": "logs for k8up for nextcloud",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 855 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"nextcloud\", container=\"backup\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "🐙 PeerTube",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - PeerTube",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 156 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - PeerTube",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 156 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - PeerTube",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 156 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - PeerTube",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 162 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - PeerTube",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 162 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - PeerTube",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 162 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for PeerTube",
     "type": "logs",
     "description": "logs for k8up for PeerTube",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 168 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"peertube\", container=\"backup\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "👥 Zitadel Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Zitadel",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 340 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - zitadel",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 340 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{instance=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - Zitadel",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 340 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Zitadel",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 384 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Zitadel",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 384 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Zitadel",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 384 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for Zitadel",
     "type": "logs",
     "description": "logs for k8up for zitadel",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 390 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"zitadel\", container=\"backup\"}"
      }
     ]
    }
   ]
  }
 ]
}