{
 "title": "KubeVirt VM Info",
 "description": "KubeVirt VM Info",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kubevirt_vmi_cpu_usage_seconds_total, exported_namespace)"
   },
   {
    "name": "vm",
    "label": "vm",
    "query": "label_values(kubevirt_vmi_cpu_usage_seconds_total{exported_namespace=\"$namespace\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(kubevirt_vmi_cpu_usage_seconds_total{exported_namespace=\"$namespace\", name=\"$vm\"}[5m])) by (domain, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_resident_bytes{exported_namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "IOPS Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_iops_read_total{exported_namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-{{type}}"
    }
   ]
  },
  {
   "title": "IO Traffic Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_read_traffic_bytes_total{exported_namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-{{type}}"
    }
   ]
  },
  {
   "title": "IO Time Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_read_times_ms_total{exported_namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-{{type}}"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_iops_write_total{exported_namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-{{type}}"
    }
   ]
  },
  {
   "title": "IO Traffic Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_write_traffic_bytes_total{exported_namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-{{type}}"
    }
   ]
  },
  {
   "title": "IO Time Wrtie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_write_times_ms_total{exported_namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-{{type}}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Network Traffic Receive",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_receive_bytes_total{exported_namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  },
  {
   "title": "Network Traffic Transmit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_transmit_bytes_total{exported_namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  }
 ]
}