{
 "title": "K8up backups",
 "description": "all the data we get from k8up as a dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Nextcloud Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "restic changed files during backup - Nextcloud",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"nextcloud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "restic changed directories during backup - Nextcloud",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{instance=\"nextcloud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "restic new files during backup - Nextcloud",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"nextcloud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "k8up backup restic snapshots - Nextcloud",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"nextcloud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "successful k8up jobs - Nextcloud",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"nextcloud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "failed k8up jobs - Nextcloud",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"nextcloud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Matrix Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "k8up backup restic snapshots - Matrix",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"matrix\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "restic changed files during backup - Matrix",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 20 },
   "targets": [
    {
     "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"matrix\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "successful k8up jobs - Matrix",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"matrix\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "failed k8up jobs - Matrix",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 9, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"matrix\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Zitadel Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "k8up backup restic snapshots - Zitadel",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"zitadel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "restic changed files during backup - Zitadel",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 9, "y": 32 },
   "targets": [
    {
     "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"zitadel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "successful k8up jobs - Zitadel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"zitadel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "failed k8up jobs - Zitadel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 9, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"zitadel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Home Assistant Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Home Assistant",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Home Assistant",
     "type": "stat",
     "gridPos": { "h": 7, "w": 11, "x": 9, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Home Assistant",
     "type": "stat",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Home Assistant",
     "type": "stat",
     "gridPos": { "h": 4, "w": 11, "x": 9, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Mastodon Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Mastodon",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Mastodon",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Mastodon",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Mastodon",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 10, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Netmaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Netmaker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"netmaker\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Netmaker",
     "type": "stat",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"netmaker\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Netmaker",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"netmaker\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Netmaker",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 10, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"netmaker\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}