{
 "title": "K8up backups",
 "description": "all the data we get from k8up as a dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "🦊 Forgejo Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Forgejo",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - Forgejo",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - Forgejo",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Forgejo",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Forgejo",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Forgejo",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"forgejo\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for Forgejo",
     "type": "logs",
     "description": "logs for k8up for GoToSocial",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"forgejo\", container=\"backup\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "🦥 GoToSocial Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - GoToSocial",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - GoToSocial",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - GoToSocial",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - GoToSocial",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - GoToSocial",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - GoToSocial",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"gotosocial\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for GotoSocial",
     "type": "logs",
     "description": "logs for k8up for GoToSocial",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "{namespace=\"gotosocial\", container=\"backup\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "🛜 Home Assistant Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Home Assistant",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - home assistant",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 78 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - home assistant",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 78 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Home Assistant",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Home Assistant",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Home Assistant",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for home assistant",
     "type": "logs",
     "description": "logs for k8up for home assistant",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "{namespace=\"home-assistant\", container=\"backup\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "🐘 Mastodon Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Mastodon",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 265 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - mastodon",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 265 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{instance=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - mastodon",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 265 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Mastodon",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 301 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Mastodon",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 301 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Mastodon",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 301 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"mastodon\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for mastodon",
     "type": "logs",
     "description": "logs for k8up for mastodon",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 307 },
     "targets": [
      {
       "expr": "{namespace=\"mastodon\", container=\"backup\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "💬 Matrix Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Matrix",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 254 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - Matrix",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 254 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{instance=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - Matrix",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 254 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Matrix",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 260 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Matrix",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 260 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Matrix",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 260 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"matrix\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for Matrix",
     "type": "logs",
     "description": "logs for k8up for matrix",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 265 },
     "targets": [
      {
       "expr": "{namespace=\"matrix\", container=\"backup\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Netmaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Netmaker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 285 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"netmaker\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Netmaker",
     "type": "stat",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 285 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"netmaker\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Netmaker",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 293 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"netmaker\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Netmaker",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 10, "y": 293 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"netmaker\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "☁️ Nextcloud Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Nextcloud",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 298 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - Nextcloud",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 298 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{instance=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - Nextcloud",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 298 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Nextcloud",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 304 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Nextcloud",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 304 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Nextcloud",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 304 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"nextcloud\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for Nextcloud",
     "type": "logs",
     "description": "logs for k8up for nextcloud",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 309 },
     "targets": [
      {
       "expr": "{namespace=\"nextcloud\", container=\"backup\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "🐙 PeerTube",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - PeerTube",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - PeerTube",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{namespace=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - PeerTube",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - PeerTube",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - PeerTube",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - PeerTube",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"peertube\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for PeerTube",
     "type": "logs",
     "description": "logs for k8up for PeerTube",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "{namespace=\"peertube\", container=\"backup\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "👥 Zitadel Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "restic changed files during backup - Zitadel",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_files_during_backup{instance=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic changed directories during backup - zitadel",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_changed_directories_during_backup{instance=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restic new files during backup - Zitadel",
     "type": "timeseries",
     "description": "new files discovered during the backup",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_new_files_during_backup{instance=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "k8up backup restic snapshots - Zitadel",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (k8up_backup_restic_available_snapshots{instance=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "successful k8up jobs - Zitadel",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_successful_counter{jobType=\"backup\", exported_namespace=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed k8up jobs - Zitadel",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(exported_namespace) (k8up_jobs_failed_counter{jobType=\"backup\", exported_namespace=\"zitadel\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8up logs for Zitadel",
     "type": "logs",
     "description": "logs for k8up for zitadel",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "{namespace=\"zitadel\", container=\"backup\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}