{
 "title": "Nextcloud Logs",
 "description": "Nextcloud audit logs stats",
 "tags": [
  "nextcloud",
  "loki"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "label_name",
    "label": "Label Name",
    "query": {}
   },
   { "name": "label_value", "label": "Label Value", "query": "label_values($label_name)" },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Total Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Successful Login",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | message=~\"Login successful.*\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Failed Login",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | message=~\"Login failed.*\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Failed - Unique IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (remoteAddr) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | message=~\"Login failed.*\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ ip }}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Nextcloud Log Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Nextcloud Log in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Uploaded Files",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"POST|PUT|MKCOL\" | message=~\"File written.*\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Deleted Files",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"DELETE\" | message=~\"File deleted.*\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Moved/Renamed Files",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"MOVE\" | message=~\"File renamed.*\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Accessed Files",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"PUT|GET\" | message=~\"File accessed.*|Preview accessed.*\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "INFO Log Lines",
   "type": "stat",
   "description": "level 1 in log",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | level=\"1\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "WARNING Log Lines",
   "type": "stat",
   "description": "level 2 in log",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | level=\"2\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Downloaded Shared Files",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"GET\" | message=~\".*shared.*accesse.*\" | url=~\".*download.*\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Accessed Shared Files",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"GET\" | message=~\".*shared.*accesse.*\" | url!~\".*download.*\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Shared Files",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"POST\" | message=~\".*shared.*\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Unshared Files",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"DELETE\" | message=~\".*unshared.*\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "ERROR Log Lines",
   "type": "stat",
   "description": "level 3 in log",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | level=\"3\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "FATAL Log Lines",
   "type": "stat",
   "description": "level 4 in log",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | level=\"4\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Successful Login by User",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (user) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | message=~\"Login successful.*\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Nextcloud Recent Log",
   "type": "logs",
   "gridPos": { "h": 21, "w": 16, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | level=\"1\" | line_format \"➡️❕ IP {{.remoteAddr}} {{.method}} {{.url }} with ? {{.user}} ? {{.message }} \""
    },
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | level=\"2\" | line_format \"➡️⚠️ IP {{.remoteAddr}} {{.method}} {{.url }} with ? {{.user}} ? {{.message }} \""
    },
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | level=\"3\" | line_format \"➡️? IP {{.remoteAddr}} {{.method}} {{.url }} with ? {{.user}} ? {{.message }} \""
    },
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | level=\"4\" | line_format \"➡️☠️ IP {{.remoteAddr}} {{.method}} {{.url }} with ? {{.user}} ? {{.message }} \""
    }
   ]
  },
  {
   "title": "Failed Login by User",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (username) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | message=~\"Login failed.*\" | pattern `<_>Login failed: <username> (Remote IP: <_>` | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ username }}"
    }
   ]
  },
  {
   "title": "Successful Login Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Login by User - Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | message=~\"Login successful.*\" | __error__=\"\" [$__interval]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Successful Login - Details",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | message=~\"Login successful.*\" | __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "Failed Login Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Login by User - Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (username) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | message=~\"Login failed.*\" | pattern `<_>Login failed: <username> (Remote IP: <_>` | __error__=\"\" [$__interval]))",
       "legendFormat": "{{ username }}"
      }
     ]
    },
    {
     "title": "Failed Login - Details",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | message=~\"Login failed.*\" | pattern `<_>Login failed: <username> (Remote IP: <_>` | __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "Upload Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uploaded Files by User - Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"POST|PUT|MKCOL\" | message=~\"File written.*\" | __error__=\"\" [$__interval]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Uploaded Files - Details",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"POST|PUT|MKCOL\" | message=~\"File written.*\" | pattern `<_>File written to: \\\"<uploaded_file>\\\"\"<_>` | __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "Delete Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deleted Files by User - Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"DELETE\" | message=~\"File deleted.*\" | __error__=\"\" [$__interval]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Deleted Files - Details",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"DELETE\" | message=~\"File deleted.*\" | pattern `<_>File deleted: \\\"<deleted_file>\\\"\"<_>` | __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "Renamed/Moved Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Renamed/Moved Files by User - Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"MOVE\" | message=~\"File renamed.*\" | __error__=\"\" [$__interval]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Renamed/Moved Files - Details",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"MOVE\" | message=~\"File renamed.*\" | pattern `<_>File renamed: \\\"<original_file>\\\" to \\\"<renamed_or_moved_file>\\\"\"<_>` | __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "Accessed Files Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accessed Files by User - Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"PUT|GET\" | message=~\"File accessed.*|Preview accessed.*\" | __error__=\"\" [$__interval]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Accessed Files - Details",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"PUT|GET\" | message=~\"File accessed.*|Preview accessed.*\" | pattern `<_>File accessed: \\\"<accessed_file>\\\"\"<_>` | __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "Shared Files Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shared Files by User - Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"POST\" | message=~\".*shared.*\" | __error__=\"\" [$__interval]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Shared Files - Details",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"POST\" | message=~\".*shared.*\" | pattern `<_>The <_> \\\"<shared_file>\\\" with ID<_>` | __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "Unshared Files Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unshared Files by User - Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"DELETE\" | message=~\".*unshared.*\" | __error__=\"\" [$__interval]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Unshared Files - Details",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"DELETE\" | message=~\".*unshared.*\" | pattern `<_>The <_> \\\"<unshared_file>\\\" with ID<_>` | __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "Downloaded Shared Files Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downloaded Shared Files by User - Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"GET\" | message=~\".*shared.*accesse.*\" | url=~\".*download.*\" | __error__=\"\" [$__interval]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Downloaded Shared Files - Details",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"GET\" | message=~\".*shared.*accesse.*\" | url=~\".*download.*\" | pattern `<_>the token \\\"<download_token>\\\" by \\\"<shared_by_username>\\\" has <_>` | __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "Accessed Shared Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accessed Shared Files by User - Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"GET\" | message=~\".*shared.*accesse.*\" | url!~\".*download.*\" | __error__=\"\" [$__interval]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Accessed Shared Files - Details",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | method=~\"GET\" | message=~\".*shared.*accesse.*\" | url!~\".*download.*\" | pattern `<_>the token \\\"<accessed_token>\\\" by \\\"<shared_by_username>\\\" has <_>` | __error__=\"\""
      }
     ]
    }
   ]
  }
 ]
}